language: ruby
rvm:
  - 2.3.0
  - 2.2
  - 2.1
  - 2.0
sudo: false
cache: bundler
install: bundle install --jobs=1
before_script: cp ./spec/config/database.yml.travis ./spec/config/database.yml
script: bundle exec rake spec rubocop
